# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project 2 - Animations' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for Project 2 - Animations
  pod 'lottie-ios'
  
end
